version: '4'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: ecomm_db
      POSTGRES_USER:
      POSTGRES_PASSWORD:
    ports:
      - "5433:5432"
    volumes:
      - ./docker/pgdata:/var/lib/postgresql/data